# Generated by Django 5.1.3 on 2024-12-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='donor_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='donor_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='mobile_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='mobile_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
