# Generated by Django 5.1.3 on 2024-12-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_blooddonor_donor_address_blooddonor_donor_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodDonor',
        ),
    ]
