# Generated by Django 5.1.3 on 2024-12-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_delete_blooddonor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('health_issue', models.CharField(max_length=200)),
                ('blood_type', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
            ],
        ),
    ]
