# Generated by Django 5.1.3 on 2024-12-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_blooddonor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodDonor',
        ),
    ]
