# Generated by Django 5.1.3 on 2025-01-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_blooddonor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='collection_status',
            field=models.BooleanField(default=False),
        ),
    ]
