# Generated by Django 5.1.3 on 2025-01-13 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_blooddonor_collection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonor',
            name='quantity',
        ),
        migrations.CreateModel(
            name='DonationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blood_type', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.blooddonor')),
            ],
        ),
    ]
