# Generated by Django 5.1.3 on 2025-01-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_remove_blooddonor_quantity_donationlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonor',
            name='collection_status',
        ),
    ]
