# Generated by Django 5.1.3 on 2025-01-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_remove_blooddonor_collection_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodRequest',
        ),
    ]
