# Generated by Django 5.1.3 on 2025-01-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_bloodrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodRequest',
        ),
    ]
