# Generated by Django 5.1.3 on 2025-01-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_userbloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbloodrequest',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
