# Generated by Django 5.1.3 on 2025-01-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_supplylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplyList',
        ),
    ]
